### ISSUE TITLE
Can't update V1.1.00.26_NEWT16B3 --> DGND3700v2_NEWT16B6.img

### ISSUE THREAD

**Issue by VincentYbarra** [ntadmin/DGND3700v2#40]
What's the best way around this? 

Thanks.

**Comment by ntadmin** [comment]
Hmmm, not experienced this one. Could you explain what does (and doesn't!) happen please?

A solution may be to 'update' to the stock Netgear firmware, and then to update from there to NEWTB6, but without further info it's hard to say.

Just to clarify: I went from B3 to B4, and B4 completely trashed the update utility and I has to do a full reset of the router right back to stock firmware and start again. This is why B4 was withdrawn. But I haven't experience any problems with updating B3.

Sometimes - say 1 in 20 - the upgrade simply doesn't work.

If you are running the router with a PPPoE link to the modem, you need to take out that connection for a minute or two before doing the upgrade for it to work. (See [here](https://community.netgear.com/t5/DSL-Modems-Routers/DGND3700v2-Firware-upload-fails/m-p/1109608#U1109608))

Finally, it can be slow!!

**Comment by ntadmin** [comment]
Further info: I don';t know why, but sometimes the updates stall in the middle of the upload. I have only experienced this since switching to using a separate modem for the VDSL and connecting to it from PPPoE port.

My solution is to unplug the PPPoE line, wait a minute or two and then do the update. However, if this fails, when the machine reboots, don't plug the PPPoE line back in. Simply try the update again and it then seems to work.

Any suggestions as to why this might be are welcome.

**Comment by VincentYbarra** [comment]
Sorry forgot to update!

 Unplugging the PPPoE line fixed it!

**Comment by ntadmin** [comment]
Glad it worked for you!
